#![deny(clippy::pedantic)]
#![deny(clippy::nursery)]

use std::{
    collections::BTreeSet,
    fs::File,
    io::{BufRead, BufReader, Write},
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use chrono::NaiveDate;
use hledger_parse::{Amount, Price, parse_journal};
use rust_decimal::Decimal;
use yahoo_finance_api as yahoo;

/// Fetch daily prices for all commodities in the journal
pub async fn update_daily_prices(base_currency: &str) -> Result<()> {
    let journal_file_path =
        std::env::var("LEDGER_FILE").context("LEDGER_FILE environment variable is not set")?;

    let file_contents =
        std::fs::read_to_string(&journal_file_path).context("Couldn't read journal file")?;

    let journal_dir = PathBuf::from(&journal_file_path)
        .parent()
        .map(|v| v.to_owned())
        .unwrap_or_else(|| PathBuf::from("."));

    let base_path = Some(journal_dir.clone());

    let mut input = file_contents.as_str();
    let journal = parse_journal(&mut input, base_path).context("Failed to parse journal file")?;

    // Collect all commodities except the base currency
    let mut commodities: BTreeSet<String> = BTreeSet::new();
    for commodity in journal.commodities() {
        let name = commodity.name.to_string();
        if name != base_currency {
            commodities.insert(name);
        }
    }

    if commodities.is_empty() {
        println!("No commodities found (excluding {})", base_currency);
        return Ok(());
    }

    let provider = yahoo::YahooConnector::new().context("Could not create YahooConnector")?;

    // Fetch prices for each commodity
    for commodity in commodities {
        let prices_file = journal_dir.join(format!("{commodity}.journal"));

        // Get the latest date from existing file if it exists
        let latest_date = if prices_file.exists() {
            get_latest_price_date(&prices_file)?
        } else {
            None
        };

        // Fetch from Yahoo
        let response = provider
            .get_quote_range(&commodity, "1d", "10y")
            .await
            .with_context(|| format!("Failed to fetch data for {commodity}"))?;

        let quotes = response
            .quotes()
            .context("Could not extract quotes from response")?;

        // Build prices, filtering out dates we already have
        let mut new_prices: Vec<Price> = quotes
            .iter()
            .filter_map(|quote| {
                // Convert Unix timestamp to date using chrono
                let datetime = chrono::DateTime::from_timestamp(quote.timestamp, 0)?;
                let date = datetime.naive_utc().date();

                // Skip if we already have this date
                if let Some(latest) = latest_date {
                    if date <= latest {
                        return None;
                    }
                }

                Some(Price {
                    date,
                    commodity: format!("\"{}\"", commodity.clone()),
                    amount: Amount {
                        currency: base_currency.to_string(),
                        value: Decimal::from_f64_retain(quote.close)
                            .unwrap_or_default()
                            .round_dp(2),
                    },
                })
            })
            .collect();

        if new_prices.is_empty() {
            println!("No new prices for {commodity}");
            continue;
        }

        // Sort by date ascending
        new_prices.sort_by(|a, b| a.date.cmp(&b.date));

        // Write to file (append mode if exists, create if not)
        let mut file = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&prices_file)
            .context("Couldn't open prices file")?;

        // Only write header if file is empty
        let file_is_empty = prices_file.metadata().map(|m| m.len() == 0).unwrap_or(true);

        if file_is_empty {
            writeln!(
                file,
                "; Generated by {}",
                concat!(env!("CARGO_PKG_NAME"), " V", env!("CARGO_PKG_VERSION"))
            )
            .context("Failed writing to prices file")?;
        }

        let price_count = new_prices.len();
        for price in new_prices {
            writeln!(file, "{}", price).context("Failed writing to prices file")?;
        }

        println!("Updated {commodity}: {} new prices", price_count);
    }

    Ok(())
}

/// Helper function to get the latest price date from a prices file
fn get_latest_price_date(prices_file: &Path) -> Result<Option<NaiveDate>> {
    let file = File::open(prices_file).context("Couldn't open prices file")?;
    let reader = BufReader::new(file);

    let mut latest_date: Option<NaiveDate> = None;

    for line in reader.lines() {
        let line = line.context("Failed to read line from prices file")?;
        let trimmed = line.trim_start();

        if !trimmed.starts_with('P') {
            continue;
        }

        // Parse "P YYYY-MM-DD ..." format
        let parts: Vec<&str> = trimmed.split_whitespace().collect();
        if parts.len() >= 2 {
            if let Ok(date) = NaiveDate::parse_from_str(parts[1], "%Y-%m-%d") {
                if latest_date.is_none() || date > latest_date.unwrap() {
                    latest_date = Some(date);
                }
            }
        }
    }

    Ok(latest_date)
}
