#![deny(clippy::pedantic)]
#![deny(clippy::nursery)]

use anyhow::{Context, Result};
use chrono::NaiveDate;
use hledger_parse::{Amount, Description, Posting, Price, Status, Transaction, parse_journal};
use rust_decimal::Decimal;
use serde::Deserialize;
use std::{
    collections::BTreeSet,
    fs::File,
    io::{BufRead, BufReader, Write},
    path::{Path, PathBuf},
};
use yahoo_finance_api as yahoo;

/// Fetch daily prices for all commodities in the journal
///
/// # Errors
///
/// Returns an error if:
/// - The `LEDGER_FILE` environment variable is not set
/// - The journal file cannot be read
/// - The journal file cannot be parsed
/// - Yahoo Finance API calls fail
/// - Files cannot be opened or written to
pub async fn update_daily_prices(base_currency: &str) -> Result<()> {
    let journal_file_path =
        std::env::var("LEDGER_FILE").context("LEDGER_FILE environment variable is not set")?;

    let file_contents =
        std::fs::read_to_string(&journal_file_path).context("Couldn't read journal file")?;

    let journal_dir = PathBuf::from(&journal_file_path)
        .parent()
        .map_or_else(|| PathBuf::from("."), std::borrow::ToOwned::to_owned);

    let base_path = Some(journal_dir.clone());

    let mut input = file_contents.as_str();
    let journal = parse_journal(&mut input, base_path).context("Failed to parse journal file")?;

    let commodities = collect_commodities(&journal, base_currency);

    if commodities.is_empty() {
        println!("No commodities found (excluding {base_currency})");
        return Ok(());
    }

    let provider = yahoo::YahooConnector::new().context("Could not create YahooConnector")?;

    for commodity in commodities {
        update_commodity_prices(&provider, &journal_dir, &commodity, base_currency).await?;
    }

    Ok(())
}

/// Collect all commodities except the base currency
fn collect_commodities(journal: &hledger_parse::Journal, base_currency: &str) -> BTreeSet<String> {
    journal
        .commodities()
        .iter()
        .map(|c| c.name.clone().trim_matches('"').trim().to_string())
        .filter(|name| name != base_currency)
        .collect()
}

/// Update prices for a single commodity
///
/// # Errors
///
/// Returns an error if Yahoo Finance API calls fail or file operations fail.
async fn update_commodity_prices(
    provider: &yahoo::YahooConnector,
    journal_dir: &Path,
    commodity: &str,
    base_currency: &str,
) -> Result<()> {
    let prices_file = journal_dir.join(format!("{commodity}.journal"));

    let latest_date = if prices_file.exists() {
        get_latest_price_date(&prices_file)?
    } else {
        None
    };

    let response = provider
        .get_quote_range(commodity, "1d", "10y")
        .await
        .with_context(|| format!("Failed to fetch data for {commodity} from Yahoo Finance API"))?;

    let quotes = response.quotes().with_context(|| {
        format!(
            "Could not extract quotes for '{commodity}' - \
                 Yahoo Finance returned an empty dataset. \
                 This could mean: invalid ticker, no data available, or rate limiting"
        )
    })?;

    let new_prices = build_new_prices(&quotes, commodity, base_currency, latest_date);

    if new_prices.is_empty() {
        println!("No new prices for {commodity}");
        return Ok(());
    }

    write_prices(&prices_file, &new_prices, commodity)?;

    Ok(())
}

/// Build a list of new prices, filtering out already-recorded dates
fn build_new_prices(
    quotes: &[yahoo_finance_api::Quote],
    commodity: &str,
    base_currency: &str,
    latest_date: Option<NaiveDate>,
) -> Vec<Price> {
    let mut prices: Vec<Price> = quotes
        .iter()
        .filter_map(|quote| {
            let datetime = chrono::DateTime::from_timestamp(quote.timestamp, 0)?;
            let date = datetime.naive_utc().date();

            if let Some(latest) = latest_date
                && date <= latest
            {
                return None;
            }

            Some(Price {
                date,
                commodity: format!("\"{commodity}\""),
                amount: Amount {
                    currency: base_currency.to_string(),
                    value: Decimal::from_f64_retain(quote.close)
                        .unwrap_or_default()
                        .round_dp(2),
                },
            })
        })
        .collect();

    prices.sort_by_key(|a| a.date);
    prices
}

/// Write prices to file
///
/// # Errors
///
/// Returns an error if the file cannot be opened or written to.
fn write_prices(prices_file: &Path, prices: &[Price], commodity: &str) -> Result<()> {
    let mut file = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(prices_file)
        .context("Couldn't open prices file")?;

    let file_is_empty = prices_file.metadata().map_or(true, |m| m.len() == 0);

    if file_is_empty {
        writeln!(
            file,
            "; Generated by {}",
            concat!(env!("CARGO_PKG_NAME"), " V", env!("CARGO_PKG_VERSION"))
        )
        .context("Failed writing to prices file")?;
    }

    for price in prices {
        writeln!(file, "{price}").context("Failed writing to prices file")?;
    }

    println!("Updated {commodity}: {} new prices", prices.len());

    Ok(())
}

/// Helper function to get the latest price date from a prices file
///
/// # Errors
///
/// Returns an error if the file cannot be read.
fn get_latest_price_date(prices_file: &Path) -> Result<Option<NaiveDate>> {
    let file = File::open(prices_file).context("Couldn't open prices file")?;
    let reader = BufReader::new(file);

    let mut latest_date: Option<NaiveDate> = None;

    for line in reader.lines() {
        let line = line.context("Failed to read line from prices file")?;
        let trimmed = line.trim_start();

        if !trimmed.starts_with('P') {
            continue;
        }

        let parts: Vec<&str> = trimmed.split_whitespace().collect();
        if parts.len() >= 2
            && let Ok(date) = NaiveDate::parse_from_str(parts[1], "%Y-%m-%d")
        {
            latest_date = Some(latest_date.map_or(date, |latest| date.max(latest)));
        }
    }

    Ok(latest_date)
}

pub async fn import_statements(csv: &str) -> Result<()> {
    let file = std::fs::read_to_string(csv)?;
    let mut rdr = csv::ReaderBuilder::new()
        .has_headers(true)
        .from_reader(file.as_bytes());

    let mut transactions: Vec<Transaction> = Vec::new();
    for result in rdr.deserialize() {
        let record: CSVTransaction = result?;

        transactions.push(Transaction {
            primary_date: record.date,
            secondary_date: Some(record.rentedatum),
            status: Status::Cleared,
            code: Some("12345".to_string()),
            description: Description {
                payee: None,
                note: Some(record.omschrijving),
            },
            postings: vec![
                Posting {
                    status: Status::Cleared,
                    account: "assets:cash".into(),
                    amount: Some(Amount {
                        currency: record.currency,
                        value: record.transactiebedrag,
                    }),
                    unit_price: None,
                    total_price: None,
                    balance_assertion: Some(Amount {
                        currency: record.currency,
                        value: record.eindsaldo,
                    }),
                },
                Posting {
                    status: Status::Cleared,
                    account: "TODO".into(),
                    amount: Some(Amount {
                        currency: "EUR".into(),
                        value: dec!(5),
                    }),
                    unit_price: None,
                    total_price: None,
                    balance_assertion: None,
                },
            ],
            tags: vec![
            //         Tag {
            //             name: "tag1".to_string(),
            //             value: Some("some value".to_string()),
            //         },
            //         Tag {
            //             name: "tag2".to_string(),
            //             value: None,
            //         },
            ],
        });
    }
    Ok(())
}

#[derive(Debug, serde::Deserialize)]
struct CSVTransaction {
    #[serde(rename = "Rekeningnummer")]
    account_number: String,
    #[serde(rename = "Muntsoort")]
    currency: String,
    #[serde(
        rename = "Transactiedatum",
        deserialize_with = "deserialize_naive_date"
    )]
    date: NaiveDate,
    #[serde(rename = "Rentedatum", deserialize_with = "deserialize_naive_date")]
    rentedatum: NaiveDate,
    #[serde(rename = "Beginsaldo")]
    beginsaldo: Decimal,
    #[serde(rename = "Eindsaldo")]
    eindsaldo: Decimal,
    #[serde(rename = "Transactiebedrag")]
    transactiebedrag: Decimal,
    #[serde(rename = "Omschrijving")]
    omschrijving: String,
}
fn deserialize_naive_date<'de, D: serde::Deserializer<'de>>(d: D) -> Result<NaiveDate, D::Error> {
    let s = String::deserialize(d)?;
    NaiveDate::parse_from_str(&s, "%Y%m%d").map_err(serde::de::Error::custom)
}
